# Generated by Django 3.0.7 on 2020-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
