# Generated by Django 3.0.7 on 2020-08-16 19:14

import django.core.files.storage
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200816_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(base_url='/images//', location='/home/g/django/myApp/images/'), upload_to=main.models.image_directory_path),
        ),
    ]
